replicaCount: 1

image:
  repository: ghcr.io/it-top-ai-bot/ai-executor
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ghcr-credentials

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: "traefik"
  host: ""
  tls: false

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    memory: "2Gi"

config:
  springProfile: "dev,kubernetes"
  serverPort: "8080"
  s3Bucket: "homeworks-solutions"
  configServer:
    host: "config-server-dev.dev.svc.cluster.local:8080"
  otel:
    endpoint: "http://192.168.0.160:4318"

vault:
  secretPath: "dev/ai-executor"

secretStore:
  name: "vault-backend"
  kind: "SecretStore"
