replicaCount: 1

image:
  repository: ghcr.io/it-top-ai-bot/tg-bot
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ghcr-credentials

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  springProfile: "dev"
  serverPort: "8080"
  backendBaseUrl: "http://api-gateway-dev.dev.svc.cluster.local:8080"

vault:
  secretPath: "dev/tg-bot"

secretStore:
  name: "vault-backend"
  kind: "SecretStore"
