replicaCount: 1

image:
  repository: ghcr.io/it-top-ai-bot/tg-bot
  pullPolicy: IfNotPresent

ingress:
  enabled: false

config:
  springProfile: "prod,kubernetes"
  backendBaseUrl: "http://api-gateway-prod.prod.svc.cluster.local:8080"
  journalServiceActuatorUrl: "http://journal-service-prod.prod.svc.cluster.local:8080"
  webhookHost: "https://bot.actimate.ru"
  proxyHost: "vpn.internal"
  proxyPort: "7890"
  configServer:
    host: "config-server.infra.svc.cluster.local"
    port: "8080"
  otel:
    endpoint: "http://192.168.0.160:4318"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    memory: "512Mi"

vault:
  secretPath: "prod/tg-bot"
