{{- if .Values.services.telegram.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.services.telegram.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.services.telegram.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Values.services.telegram.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.services.telegram.tokenSecretKey | quote }}
      remoteRef:
        key: {{ .Values.vault.secretPath | quote }}
        property: {{ .Values.services.telegram.vaultProperty | quote }}
{{- end }}
