replicaCount: 1

image:
  repository: ghcr.io/it-top-ai-bot/api-gateway
  pullPolicy: Always
  tag: "sha-dd53a0b"

ingress:
  enabled: false

config:
  configServer:
    host: "config-server.infra.svc.cluster.local"
    port: "8080"
  otel:
    endpoint: "http://192.168.0.160:4318"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    memory: "512Mi"

probes:
  startup:
    path: /actuator/health
    periodSeconds: 5
    failureThreshold: 30
