replicaCount: 1

image:
  repository: ghcr.io/it-top-ai-bot/api-gateway
  pullPolicy: Always
  tag: "sha-361b350"

ingress:
  enabled: true
  className: "traefik"
  host: "api-dev.YOUR_DOMAIN"
  tls: false

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
