context:
  argocdUrl: "https://argocd.actimate.ru"
  environment: "dev"

services:
  telegram:
    enabled: false
    tokenSecretKey: "telegram-token"

defaultTriggers:
  - on-deployed
  - on-health-degraded
  - on-sync-failed
  - on-sync-status-unknown

subscriptions: [ ]
# Example:
# subscriptions:
#   - recipients:
#       - "telegram:-1001234567890"
#     triggers:
#       - on-deployed
#       - on-sync-failed
#       - on-health-degraded
#     selector: "notifications=enabled"
