replicaCount: 1

image:
  repository: ghcr.io/it-top-ai-bot/config-server
  pullPolicy: Always
  tag: "latest"

config:
  adminServer:
    url: "http://admin-server-dev.dev.svc.cluster.local:8090"
    serviceBaseUrl: "http://config-server-dev.dev.svc.cluster.local:8888"
  otel:
    endpoint: "http://otel-collector.monitoring.svc.cluster.local:4318"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    memory: "512Mi"
