kafkaBootstrapServers: "192.168.0.219:9092"

connector:
  slotName: journal_outbox_slot
  publicationName: journal_outbox_pub
  topicPrefix: journal
  tableIncludeList: "public.outbox_event"
  snapshotMode: initial

vault:
  secretPath: "dev/debezium"

secretStore:
  name: "vault-backend"
  kind: "SecretStore"
