replicaCount: 1

image:
  repository: ghcr.io/it-top-ai-bot/journal-service
  pullPolicy: Always
  tag: "latest"

ingress:
  enabled: false
  className: "traefik"
  host: "journal-dev.YOUR_DOMAIN"
  tls: false

config:
  springProfile: "dev"
  redis:
    host: "redis-master.dev.svc.cluster.local"
    port: "6379"
  journal:
    baseUrl: "https://YOUR_JOURNAL_API_URL"
    syncInterval: "3600000"

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
