replicaCount: 1

image:
  repository: ghcr.io/it-top-ai-bot/tg-bot
  pullPolicy: Always
  tag: "sha-c6b486e"

ingress:
  enabled: false

config:
  backendBaseUrl: "http://api-gateway-dev.dev.svc.cluster.local:8080"
  webhookHost: "https://dev-bot.actimate.ru"
  proxyHost: "192.168.0.148"
  proxyPort: "7890"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
