apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-server-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/it-top-ai-bot/admin-server
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/app.helm.image-spec: image.repository:image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/IT-Top-AI-Bot/gitops
    targetRevision: main
    path: charts/admin-server
    helm:
      valueFiles:
        - ../../envs/dev/admin-server-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 1m
