apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/IT-Top-AI-Bot/gitops
    targetRevision: main
    path: charts/dev-infra
    helm:
      valueFiles:
        - ../../../envs/dev/infra-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
