apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journal-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/gitops
    targetRevision: main
    path: charts/journal-service
    helm:
      valueFiles:
        - ../../../envs/dev/journal-service-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 1m
