{ { - if .Values.ingress.enabled - } }
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { { include "journal-service.fullname" . } }
  namespace: { { .Release.Namespace } }
  labels:
    { { - include "journal-service.labels" . | nindent 4 } }
spec:
  { { - if .Values.ingress.className } }
  ingressClassName: { { .Values.ingress.className } }
  { { - end } }
  { { - if .Values.ingress.tls } }
  tls:
    - hosts:
        - { { .Values.ingress.host } }
      secretName: { { include "journal-service.fullname" . } }-tls
  {{- end }}
  rules:
      - host: { { .Values.ingress.host } }
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: { { include "journal-service.fullname" . } }
                  port:
                    name: http
  { { - end } }
