context:
  argocdUrl: "https://argocd.actimate.ru"
  environment: "shared"

serviceAccount:
  create: true
  name: "external-secrets"

vault:
  address: "https://vault.actimate.ru"
  mountPath: "secret"
  kubernetesMountPath: "kubernetes"
  role: "argocd-role"
  secretPath: "shared/argocd-notifications"

secretStore:
  create: true
  name: "vault-backend"
  kind: "SecretStore"

services:
  telegram:
    enabled: true
    secretName: "argocd-notifications-secret"
    tokenSecretKey: "telegram-token"
    vaultProperty: "TELEGRAM_TOKEN"
    refreshInterval: "1h"

defaultTriggers:
  - on-deployed
  - on-health-degraded
  - on-sync-failed
  - on-sync-status-unknown

subscriptions:
  - recipients:
      - "telegram:7730540142"
    triggers:
      - on-deployed
      - on-sync-failed
      - on-health-degraded
    selector: "notifications=enabled"
# Example:
# subscriptions:
#   - recipients:
#       - "telegram:-1001234567890"
#     triggers:
#       - on-deployed
#       - on-sync-failed
#       - on-health-degraded
#     selector: "notifications=enabled"
