apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.externalSecretIgnoreDifferences.enabled }}
  resource.customizations.ignoreDifferences.external-secrets.io_ExternalSecret: |
    managedFieldsManagers:
{{- range .Values.externalSecretIgnoreDifferences.managedFieldsManagers }}
      - {{ . | quote }}
{{- end }}
    jsonPointers:
{{- range .Values.externalSecretIgnoreDifferences.jsonPointers }}
      - {{ . | quote }}
{{- end }}
    jqPathExpressions:
{{- range .Values.externalSecretIgnoreDifferences.jqPathExpressions }}
      - {{ . | quote }}
{{- end }}
{{- end }}
